name: Apparatus Docs Deploy Trigger

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Current API version can be found here: https://docs.github.com/en/rest/about-the-rest-api/api-versions?apiVersion=2022-11-28
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="Topl"
          repo_name="Knowledge-Base"
          event_type="trigger-workflow"
          service=${{ github.event.inputs.target_service }}"
          version="${{ github.event.inputs.target_version }}"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"
