name: Apparatus Repo Workflow Trigger

on:
  workflow_dispatch:
    inputs:
      repo_owner:
        description: "Name of the GitHub repo owner/org. ex: Apparatus."
        default: "Topl"
        required: false
        type: string
      repo_name:
        description: "Name of the GitHub repo. ex: Knowledge-Base."
        default: "Knowledge-Base"
        required: false
        type: string
      event_type:
        description: "Name of the event that triggers the repository_dispatch. Useful for selectively running dispatched workflows."
        default: "trigger_workflow"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Current API version can be found here: https://docs.github.com/en/rest/about-the-rest-api/api-versions?apiVersion=2022-11-28
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          service=${{ github.event.inputs.target_service }}"
          version="${{ github.event.inputs.target_version }}"
          branch="${{ github.ref_name }}"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ inputs.repo_owner }}/${{ inputs.repo_name }}/dispatches \
            -d "{\"event_type\": \"${{ inputs.event_type }}\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"branch\": \"$branch\", \"unit\": false, \"integration\": true}}"
